#
# This file is part of Python Client Library for STAC.
# Copyright (C) 2019 INPE.
#
# Python Client Library for STAC is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.
#

language: python

cache:
    directories:
        - $HOME/.cache/pip

branches:
    only:
        - master
        - b-0.7.0
        - b-0.8.0
        - b-0.8.1

dist: bionic

python:
    - "3.7"

before_install:
    - pip install --upgrade pip
    - pip install --upgrade setuptools
    - pip install --upgrade wheel

install:
    - pip install -e .[tests,docs]

script:
    - ./run-test.sh

after_success:
    - coveralls

notifications:
    slack: 
        rooms:
            - secure: "injKqTR0s9nv1u49G04HrcRmG5OZUTTrbVSXD/irCWFj3ySsQmYsMffHdEl4qZOtZAjyO1xxIiHTjFqHMwUD9/9P8Cl6gRLNMPs5BawtG4XLU6K6GcmjfqAHxd5VS/G+VLdebdyKmX+Spg5Vw6Qf7TiZoOn28xse7J3B96r6TknPUv6P0hDRB1/fZYEodAxtBnfd45dVqro8QfJBDBsOMyym9GA1r7yvM7o4JMFI0ymNaomc07OrOLvRDH3QoOS9RbWKdMowNw9IL6VT+9xuOrWh3pSgs1O+cOoTfekQjCf0CjF8BKJzMO2kUwKi6lEMTmwF7aVbSBp4PwaAeiN/UKpPRustHE8IijyJXi2kUVKq3cLzv0If0BuCj0YuCyRRqmIdeMtxv9ZCdLLXmhaOp89InqZQdKDqIMu77Il2i2qoZRBLfmv26okLffd5YjglqOolRhMy3hvg44Is0PImFdepqHuixdej+VPUUvD5ZD7UMtCMW1oayHGtEZNLSTurowJ5m5Zp19QWJsH4Rg1jjEc91AEkVv6YlvRA5UbvNGND238ghYPydTtNahaEm705oRMo98SH57G4PmZx4H8ZuHelJtC7pjzUE9yPw3SYdlANvkz/xGcZlT8ciw4Qq+Kz83FptF6obtevMXB09EoqYKdeUZoplE1AEluq3ODssr0="
        on_sucess: always
