#
# This file is part of Python Client Library for STAC.
# Copyright (C) 2019-2020 INPE.
#
# Python Client Library for STAC is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.
#

language: python

os: linux

cache:
    directories:
        - $HOME/.cache/pip

git:
    quiet: true
    submodules: false

branches:
    only:
        - master
        - b-0.7.0
        - b-0.8.0
        - b-0.8.1
        - b-0.9.0

dist: bionic

python:
    - 3.7

before_install:
    - pip install --upgrade pip
    - pip install --upgrade setuptools

install:
    - pip install -e .[tests,docs]

script:
    - ./run-tests.sh

after_success:
    - coveralls